### ISSUE TITLE
服务安装运行后，在服务管理器中查看属性中的“依存关系”标签页，服务报错并停止

### ISSUE THREAD

**Issue by e4ky** [NewLifeX/NewLife.Agent#1]
日志
15:22:09.413  1 N - System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
   在 oTNQt6nEMsWjMgBHlg.pVa3WN9WWLhBKPa4QS.bSOuf9DJ87(IntPtr  , IntPtr  , IntPtr  , UInt32  , IntPtr  , UInt32&  )
   在 NewLife.Agent.Advapi32.StartServiceCtrlDispatcher(IntPtr entry)
   在 NewLife.Agent.WindowsService.Run(IHostedService service) 位置 D:\GithubProject\NewLife.Agent\NewLife.Agent\WindowsService.cs:行号 64
15:22:09.413  2 N - 停止服务，释放TCP服务对像===========================

**Comment by e4ky** [comment]
**运行中，手工停止服务器报错，**
![image](https://user-images.githubusercontent.com/11674702/78335726-be97a000-75c0-11ea-8805-b47346c50590.png)
日志：
15:39:41.534  1 N - System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
   在 oTNQt6nEMsWjMgBHlg.pVa3WN9WWLhBKPa4QS.bSOuf9DJ87(IntPtr  , IntPtr  , IntPtr  , UInt32  , IntPtr  , UInt32&  )
   在 NewLife.Agent.Advapi32.StartServiceCtrlDispatcher(IntPtr entry)
   在 NewLife.Agent.WindowsService.Run(IHostedService service) 位置 D:\GithubProject\NewLife.Agent\NewLife.Agent\WindowsService.cs:行号 64
15:39:41.534  2 N - 停止服务，释放TCP服务对像===========================
15:39:41.538  2 N - 【断线事件】设备“D0121707000174”，接入IP：“[::ffff:192.168.1.177]:1031”从服务器端口8888 断开
15:39:41.540  2 N - 服务停止 ProcessExit
15:39:41.540  2 N - 服务停止 ProcessExit
点重启服务按钮时也报错，
![image](https://user-images.githubusercontent.com/11674702/78335987-35cd3400-75c1-11ea-93b7-e90addf11433.png)
日志：
15:36:45.655  1 N - System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
   在 oTNQt6nEMsWjMgBHlg.pVa3WN9WWLhBKPa4QS.bSOuf9DJ87(IntPtr  , IntPtr  , IntPtr  , UInt32  , IntPtr  , UInt32&  )
   在 NewLife.Agent.Advapi32.StartServiceCtrlDispatcher(IntPtr entry)
   在 NewLife.Agent.WindowsService.Run(IHostedService service) 位置 D:\GithubProject\NewLife.Agent\NewLife.Agent\WindowsService.cs:行号 64
15:36:45.655  2 N - 停止服务，释放TCP服务对像===========================

**Comment by nnhy** [comment]
"管道已结束”，这是已知问题，在3.31的时候已经解决，更新代码试试

**Comment by e4ky** [comment]
**更新了之后问题依旧**
我的程序运行环境是：.NETFramework,Version=v4.6.1
NewLife.Core.dll  8.7.2020.403
NewLife.Agent.dll 8.7.2020.403
**日志：**
16:20:10.672  1 N - System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
   在 oTNQt6nEMsWjMgBHlg.pVa3WN9WWLhBKPa4QS.bSOuf9DJ87(IntPtr  , IntPtr  , IntPtr  , UInt32  , IntPtr  , UInt32&  )
   在 NewLife.Agent.Advapi32.StartServiceCtrlDispatcher(IntPtr entry)
   在 NewLife.Agent.WindowsService.Run(ServiceBase service) 位置 D:\GithubProject\NewLife.Agent\NewLife.Agent\WindowsService.cs:行号 81
16:20:10.672  2 N - 停止服务，释放TCP服务对像===========================
16:20:10.672  2 N - 【断线事件】设备“D0121707000174”，接入IP：“[::ffff:192.168.1.177]:1031”从服务器端口8888 断开
16:20:10.672  2 N - 服务停止 ProcessExit

**Comment by e4ky** [comment]
你发我的程序也运行了，差不多的问题，在停止或重启服务时出现。
![image](https://user-images.githubusercontent.com/11674702/78362949-89ee0d80-75ed-11ea-8a7c-f22b1ab47b76.png)

**Comment by e4ky** [comment]
此问在部分机子上会这样(win10 64 位)，生成时关闭代码优化可解决这一问题。
