### ISSUE TITLE
电脑断电后，newlife安装的服务消失了

### ISSUE THREAD

**Issue by worldofchu** [NewLifeX/NewLife.Agent#12]
win732  X86电脑，现场电脑断电后，原本注册的服务消失了。需要重新安装服务才行

**Comment by worldofchu** [comment]
请问 能解决这个bug吗。dotnet6  x86 sdk环境 win7 32 系统

**Comment by nnhy** [comment]
这是操作系统的行为，注册服务后，本质上就是调用winapi，写入操作系统数据库

**Comment by worldofchu** [comment]
不赞同！ 其它服务为啥没丢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月21日 00:16 |
| 收件人 | ***@***.***> |
| 抄送人 | worldofchu ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [NewLifeX/NewLife.Agent] 电脑断电后，newlife安装的服务消失了 (Issue #12) |

这是操作系统的行为，注册服务后，本质上就是调用winapi，写入操作系统数据库

**Comment by nnhy** [comment]
经win7x86测试，安装net6版星尘代理服务，重启后服务正常。

![image](https://github.com/NewLifeX/NewLife.Agent/assets/506367/61a1b8b8-cbab-4f73-8948-dead021fb15d)

**Comment by worldofchu** [comment]
我们就是net6啊？

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月21日 18:46 |
| 收件人 | ***@***.***> |
| 抄送人 | worldofchu ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [NewLifeX/NewLife.Agent] 电脑断电后，newlife安装的服务消失了 (Issue #12) |

经win7x86测试，安装net6版星尘代理服务，重启后服务正常。

image.png (view on web)

**Comment by nnhy** [comment]
没有出现已注册的windows服务丢失问题
