### ISSUE TITLE
新增SysVinit主机

### ISSUE THREAD

**Issue by nnhy** [NewLifeX/NewLife.Agent#16]
仔细阅读源码，发现sysvinit和systemd是两个不同的命令，它们的机制和用法大体相同，但是在细节上有许多不同的地方。
我建议新增一种IHost主机，把二次分开。然后在Agent初始化时检测需要使用哪一种。

**Comment by andywu188** [comment]
有可能在一台服务器上，sysvinit和systemd两种同时存在，如何处理？
以国内知名的宝塔面板为例，在他的软件商店安装的应用，我目前所知，都是sysvinit，NewLife.Agent安装时，会以systemd服务方式安装，那最终在一台服务器上，一定会存在两种形式

**Comment by nnhy** [comment]
如果systemd比SysVinit更先进，那就优先用它。
反之亦然

**Comment by andywu188** [comment]
已解决 https://github.com/NewLifeX/NewLife.Agent/commit/a49f82f4baeb4ade301339a3978e05b6ff9b03b5
